(async()=>{
 const s=requireLogin();if(!s)return;renderWorkspaceNav('approvals');const root=document.getElementById('pageContent');let queue=[],tab='all',query='',failures=[];
 async function load(){root.innerHTML=pageHeading('งานอนุมัติ','ตรวจสอบคำขอและดำเนินการจากพื้นที่เดียว')+'<div class="skeleton-box"></div>';
 const results=await Promise.allSettled([fetchPendingApprovals(s.Email),apiGet('getExportApprovalInbox',{email:s.Email}),fetchPettyInbox(s.Email)]);queue=[];failures=[];
 results.forEach((r,i)=>{if(r.status==='rejected'){failures.push(['ค่าใช้จ่าย','รอบเบิก','เงินสดย่อย'][i]+': '+r.reason.message);return;}if(i===0)queue.push(...r.value.map(x=>({...x,kind:'expense'})));if(i===1)queue.push(...r.value.map(x=>({...x,kind:'period'})));if(i===2){queue.push(...(r.value.toApprove||[]).map(x=>({...x,kind:'petty'})));queue.push(...(r.value.toPay||[]).map(x=>({...x,kind:'pay'})));}});queue.sort((a,b)=>new Date(a.Timestamp||a.RequestedAt)-new Date(b.Timestamp||b.RequestedAt));render();}
 const labels={all:'ทั้งหมด',expense:'ค่าใช้จ่าย',period:'รอบเบิก',petty:'เงินสดย่อย',pay:'รอจ่ายเงินสด'};
 function render(){root.innerHTML=pageHeading('งานอนุมัติ','เรียงงานเก่าก่อน เพื่อช่วยให้คำขอไม่ตกค้าง',`<button class="btn btn-secondary" id="reloadQueue">รีเฟรช</button>`)+`<div class="queue-tabs" role="tablist">${Object.entries(labels).map(([k,v])=>`<button role="tab" aria-selected="${tab===k}" class="${tab===k?'active':''}" data-tab="${k}">${v} · ${k==='all'?queue.length:queue.filter(x=>x.kind===k).length}</button>`).join('')}</div><div class="filter-toolbar"><input type="search" id="queueSearch" aria-label="ค้นหางานอนุมัติ" placeholder="ค้นหาชื่อพนักงาน รายละเอียด หรือเลขคำขอ" value="${esc(query)}"></div>${failures.length?`<div class="warn-box" role="alert">บางส่วนโหลดไม่สำเร็จ กดรีเฟรชเพื่อลองใหม่<br>${failures.map(esc).join('<br>')}</div>`:''}<div style="margin-bottom:16px;font-size:12px"><a href="${s.isGM?'inbox.html':s.isSenior?'senior-inbox.html':'manager-inbox.html'}">เปิดเครื่องมืออนุมัติหลายรายการ →</a></div><div id="queueList"></div>`;document.getElementById('reloadQueue').onclick=()=>{invalidateReadSnapshots();load();};root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});document.getElementById('queueSearch').oninput=e=>{query=e.target.value;paint();};paint();}
 function paint(){const rows=queue.filter(r=>(tab==='all'||r.kind===tab)&&[r.StaffName,r.RequesterName,r.Purpose,r.Venue,r.ID].join(' ').toLowerCase().includes(query.toLowerCase()));document.getElementById('queueList').innerHTML=rows.length?rows.map((r)=>{const href=r.kind==='period'?'export-review.html?id='+encodeURIComponent(r.ID):r.kind==='expense'?'approve.html?id='+encodeURIComponent(r.ID)+'&stage='+(r._stage||'manager'):'pc-approve.html?id='+encodeURIComponent(r.ID);const n=Number(r.Amount||r.TotalAmount||r.Total||r.PreApproveBudget||0);const age=Math.max(0,Math.floor((Date.now()-new Date(r.Timestamp||r.RequestedAt||Date.now()))/86400000));return `<article class="queue-card"><div><h3>${esc(r.StaffName||r.RequesterName||'คำขอ')}</h3><p>${esc(r.kind==='period'?'ขออนุมัติรอบเบิก':r.Purpose||r.Venue||catTH(r.Category))}</p><p>${esc(r.ID)}</p></div><div class="queue-amount">${formatCurrency(n)}<p>บาท</p></div><div class="queue-footer"><span class="subtle">${labels[r.kind]} · รอ ${age} วัน</span><a class="btn btn-secondary" href="${href}">ตรวจสอบ${r.kind==='pay'?'และจ่ายเงิน':'รายละเอียด'} →</a></div></article>`;}).join(''):emptyState(query?'ไม่พบรายการที่ค้นหา':'ไม่มีงานค้างในหมวดนี้',query?'ลองค้นหาด้วยชื่อหรือเลขคำขออื่น':'เมื่อมีคำขอที่คุณรับผิดชอบ รายการจะแสดงที่นี่');}
 await load();
})();
