(async()=>{
 const session=requireLogin();if(!session)return;renderWorkspaceNav('new');const root=document.getElementById('pageContent'),key='expense:'+session.Email.toLowerCase();
 let categories=[],rate=null,approver=null,items=[],pending=null,busy=false,metadataReady=false,saveChain=Promise.resolve();
 const fresh=()=>({id:crypto.randomUUID(),category:'',expenseDate:todayYMD(),amount:'',mileageKm:'',venue:'',origin:'',destination:'',customer:'',customerContact:'',jobNo:'',occasion:'',attendees:'',receipts:[]});
 root.innerHTML=pageHeading('สร้างคำขอเบิก','กรอกค่าใช้จ่าย แนบใบเสร็จ แล้วตรวจสอบก่อนส่ง')+'<div class="skeleton-box"></div>';

 let draft=null,storageError=false;try{draft=await DraftStore.get(key);}catch(e){storageError=true;}
 items=draft?.items?.length?draft.items:[fresh()];pending=draft?.pending||null;
 const legacy=localStorage.getItem('exion_draft_'+session.Email.toLowerCase());if(!draft&&legacy){try{const d=JSON.parse(legacy);if(d.items?.length){items=d.items.map(x=>({...fresh(),...x,receipts:[]}));showToast('กู้คืนร่างเดิมแล้ว กรุณาแนบใบเสร็จอีกครั้ง','info');}}catch(e){}}
 render();if(storageError)setSave('เครื่องนี้บันทึกร่างไม่ได้ กรุณาอย่าปิดหน้าระหว่างกรอก');else if(draft)setSave('กู้คืนร่างพร้อมไฟล์แนบ · '+new Date(draft.savedAt).toLocaleString('th-TH'));
 async function loadMetadata(){
 try{[categories,rate,approver]=await Promise.all([fetchCategories(),fetchFuelRate(session.Email),apiGet('getMyApprover')]);categories=categories.filter(c=>!['ENT','GOLF'].includes(c.Code));if(!categories.length)throw new Error('ยังไม่มีประเภทค่าใช้จ่าย กรุณาติดต่อผู้ดูแล');
 metadataReady=true;const focused=document.activeElement,id=focused?.id,start=focused?.selectionStart,end=focused?.selectionEnd;render();const next=id&&document.getElementById(id);if(next){next.focus();try{next.setSelectionRange(start,end);}catch(e){}}
 }catch(e){const box=document.getElementById('metadataState');if(box){box.textContent='โหลดประเภทและอัตราค่าใช้จ่ายไม่สำเร็จ ร่างยังอยู่ ';const retry=document.createElement('button');retry.type='button';retry.textContent='ลองใหม่';retry.onclick=()=>{retry.disabled=true;loadMetadata();};box.append(retry);}}
 }
 loadMetadata();
 function amount(it){return it.category==='FUEL'?Math.round(Number(it.mileageKm||0)*Number(rate?.rate||0)*100)/100:Number(it.amount||0);}
 function total(){return items.reduce((sum,it)=>sum+amount(it),0);}
 function setSave(text){const el=document.getElementById('saveState');if(el)el.textContent=text;}
 function save(){const snapshot={items:structuredClone(items),pending:pending?structuredClone(pending):null,savedAt:Date.now()};saveChain=saveChain.catch(()=>{}).then(()=>DraftStore.put(key,snapshot));saveChain.then(()=>setSave('บันทึกร่างและไฟล์แนบในเครื่องแล้ว · '+new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}))).catch(()=>setSave('บันทึกร่างไม่สำเร็จ พื้นที่อาจเต็ม กรุณาอย่าปิดหน้านี้'));return saveChain;}
 function field(it,name,label,type='text',opts=''){return `<div class="field ${name==='venue'?'wide':''}"><label for="${it.id}-${name}">${label}</label><input id="${it.id}-${name}" data-field="${name}" type="${type}" value="${esc(it[name])}" ${opts}><div class="error" id="${it.id}-${name}-error"></div></div>`;}
 function card(it,index){const cat=categories.find(c=>c.Code===it.category),fuel=it.category==='FUEL';return `<details class="card expense-card" open data-item="${it.id}"><summary class="expense-card-head"><h2><span class="num">${String(index+1).padStart(2,'0')}</span>${esc(cat?catTH(cat.Code):'รายการค่าใช้จ่าย')}</h2><span><button type="button" class="icon-button" data-duplicate="${it.id}" aria-label="ทำสำเนารายการ ${index+1}">${icon('plus')} ทำสำเนา</button>${items.length>1?`<button type="button" class="icon-button" data-remove="${it.id}" aria-label="ลบรายการ ${index+1}">${icon('x')}</button>`:''}</span></summary><div class="form-grid"><div class="field"><label for="${it.id}-category">ประเภทค่าใช้จ่าย *</label><select id="${it.id}-category" data-field="category"><option value="">เลือกประเภท</option>${categories.map(c=>`<option value="${esc(c.Code)}" ${it.category===c.Code?'selected':''}>${esc(catTH(c.Code))}</option>`).join('')}</select><div class="error" id="${it.id}-category-error"></div></div>${field(it,'expenseDate','วันที่ใช้จ่าย *','date',`max="${todayYMD()}"`)}${fuel?field(it,'mileageKm','ระยะทาง (กม.) *','number','min="0.1" step="0.1" inputmode="decimal"'):field(it,'amount','จำนวนเงิน (บาท) *','number','min="0.01" step="0.01" inputmode="decimal" placeholder="0.00"')}${field(it,'jobNo','เลข Job (ถ้ามี)')}${field(it,'venue','รายละเอียดค่าใช้จ่าย','text','placeholder="เช่น ค่าทางด่วนไปพบลูกค้า"')}${fuel?field(it,'origin','ต้นทาง')+field(it,'destination','ปลายทาง'):''}${field(it,'customer','ลูกค้า (ถ้ามี)','text','list="customerSuggestions"')}${field(it,'customerContact','ผู้ติดต่อ (ถ้ามี)')}${cat?.NeedClaimForm==='YES'?field(it,'occasion','วัตถุประสงค์ / โอกาส *')+field(it,'attendees','รายชื่อผู้ร่วม *'):''}</div>${fuel?`<div class="form-hint">อัตราปัจจุบัน ${formatCurrency(rate?.rate)} บาท/กม. · <b>ยอดประมาณการ</b><br>ยอดที่บันทึกจริงคำนวณจากอัตราตามรอบของวันที่ใช้จ่าย และอาจปรับตามราคาน้ำมันประจำรอบ</div>`:''}<label class="upload-area" for="${it.id}-files"><input type="file" id="${it.id}-files" data-files="${it.id}" accept="image/jpeg,image/png,image/webp,application/pdf" multiple>${icon('camera')}<div class="text">แนบใบเสร็จ ${cat?.NeedReceipt==='YES'?'*':'(ถ้ามี)'}</div><div class="sub">เลือกไฟล์ / ถ่ายภาพ · JPG, PNG, WebP, PDF · ไม่เกิน 5 MB ต่อไฟล์</div></label><div class="error" id="${it.id}-files-error" style="color:var(--bad);font-size:12px"></div><div class="attachment-list">${it.receipts.map((f,i)=>`<div class="attachment">${f.base64.startsWith('data:image/')?`<img src="${esc(f.base64)}" alt="ตัวอย่างใบเสร็จ">`:icon('receipt')}<button type="button" class="icon-button" data-preview="${it.id}:${i}"><span>${esc(f.name)}</span></button><button class="icon-button" type="button" data-file-remove="${it.id}:${i}" aria-label="ลบไฟล์ ${esc(f.name)}">${icon('x')}</button></div>`).join('')}</div></details>`;}
 function render(){root.innerHTML=pageHeading('สร้างคำขอเบิก','เพิ่มได้หลายรายการ บันทึกร่างพร้อมใบเสร็จอัตโนมัติ')+`${!metadataReady?'<div class="warn-box" id="metadataState" role="status">กำลังโหลดประเภทและอัตราค่าใช้จ่าย · กรอกข้อมูลและแนบใบเสร็จรอได้</div>':''}<div class="stepper"><span class="active"><b>1</b> กรอกรายการ</span><i></i><span><b>2</b> ตรวจสอบ</span><i></i><span><b>3</b> ส่งคำขอ</span></div>${pending?'<div class="draft-banner" role="status"><div><b>รอตรวจสอบผลการส่งครั้งก่อน</b><small>ข้อมูลชุดนี้ถูกล็อกชั่วคราว กดตรวจสอบและส่งซ้ำด้วยรหัสเดิมเพื่อป้องกันรายการซ้ำ</small></div></div>':''}<div class="expense-layout"><section><div id="expenseItems">${items.map(card).join('')}</div><button type="button" id="addItem" class="btn btn-secondary" style="width:100%;border-style:dashed!important">${icon('plus')} เพิ่มรายการใหม่</button><div class="form-footer">ค่ารับรอง / กอล์ฟ ต้อง <a href="pre-approve.html">ขออนุมัติงบล่วงหน้า →</a></div></section><aside class="expense-summary"><div class="card"><h3>สรุปคำขอ</h3><div class="summary-line"><span>รายการค่าใช้จ่าย</span><b id="itemCount">${items.length} รายการ</b></div><div class="summary-line"><span>ใบเสร็จ</span><b id="fileCount">${items.reduce((a,it)=>a+it.receipts.length,0)} ไฟล์</b></div><div class="subtle" style="margin-top:18px">ยอดรวม${items.some(it=>it.category==='FUEL')?'ประมาณการ':''} (บาท)</div><div class="total" id="formTotal">${formatCurrency(total())}</div><button class="btn btn-primary" id="reviewBtn">${pending?'ตรวจสอบและส่งซ้ำ':'ตรวจสอบก่อนส่ง →'}</button><div class="save-indicator" id="saveState" role="status">ร่างบันทึกในเครื่องนี้ เฉพาะบัญชีของคุณ</div><button class="icon-button" id="clearDraft">ล้างร่างนี้</button></div><div class="card note-card"><strong>ผู้รับอนุมัติ</strong>${esc(approver?.name||approver?.email||'ตามประเภทค่าใช้จ่ายและสายอนุมัติ')}<br>ประเภทที่ไม่ต้องอนุมัติจะบันทึกสำเร็จทันที</div></aside></div><div class="mobile-submit-bar"><div><small>รวม${items.some(it=>it.category==='FUEL')?'ประมาณการ':''} (บาท)</small><strong id="mobileTotal">${formatCurrency(total())}</strong></div><button class="btn btn-primary" id="mobileReview">${pending?'ตรวจสอบการส่ง':'ตรวจสอบก่อนส่ง'}</button></div><datalist id="customerSuggestions"></datalist>`;
 root.querySelectorAll('[data-field]').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{const it=items.find(i=>i.id===el.closest('[data-item]').dataset.item);it[el.dataset.field]=el.value;if(el.dataset.field==='category'){render();}else {document.getElementById('formTotal').textContent=formatCurrency(total());document.getElementById('mobileTotal').textContent=formatCurrency(total());}save();}));
 document.getElementById('addItem').onclick=()=>{if(items.length>=50){showToast('ส่งได้ครั้งละไม่เกิน 50 รายการ','error');return;}items.push(fresh());render();save();root.querySelector('[data-item]:last-child input')?.focus();};
 root.querySelectorAll('[data-duplicate]').forEach(b=>b.onclick=e=>{e.preventDefault();if(items.length>=50){showToast('ส่งได้ครั้งละไม่เกิน 50 รายการ','error');return;}const it=items.find(x=>x.id===b.dataset.duplicate);items.push({...structuredClone(it),id:crypto.randomUUID(),receipts:[]});render();save();showToast('ทำสำเนาข้อมูลแล้ว กรุณาแนบใบเสร็จของรายการใหม่');});
 root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async e=>{e.preventDefault();if(!await confirmDialog('ลบรายการนี้?','ข้อมูลและไฟล์แนบของรายการนี้จะถูกนำออกจากร่าง','ลบรายการ'))return;items=items.filter(x=>x.id!==b.dataset.remove);render();save();});
 root.querySelectorAll('[data-files]').forEach(input=>input.onchange=async()=>{const it=items.find(x=>x.id===input.dataset.files);try{for(const file of input.files){if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type))throw new Error('รองรับ JPG, PNG, WebP และ PDF เท่านั้น');if(file.size>5*1024*1024)throw new Error('ไฟล์ '+file.name+' ใหญ่เกิน 5 MB');if(it.receipts.length>=8)throw new Error('แนบได้ไม่เกิน 8 ไฟล์ต่อรายการ');it.receipts.push({name:file.name,base64:await fileToBase64(file)});}render();await save();}catch(e){render();save();showToast(e.message,'error');}});
 root.querySelectorAll('[data-file-remove]').forEach(b=>b.onclick=()=>{const [id,n]=b.dataset.fileRemove.split(':');items.find(x=>x.id===id).receipts.splice(Number(n),1);render();save();});
 root.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{const[id,n]=b.dataset.preview.split(':'),f=items.find(x=>x.id===id).receipts[n];if(f.base64.startsWith('data:image/'))openImageViewer(f.base64);else{const bytes=Uint8Array.from(atob(f.base64.split(',')[1]),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000);}});
 document.getElementById('clearDraft').onclick=async()=>{if(await confirmDialog('ล้างร่างนี้?','รายการและไฟล์แนบในร่างนี้จะถูกลบ','ล้างร่าง')){await saveChain.catch(()=>{});await DraftStore.remove(key);localStorage.removeItem('exion_draft_'+session.Email.toLowerCase());items=[fresh()];render();}};
 document.getElementById('reviewBtn').onclick=()=>pending?send():review();document.getElementById('mobileReview').onclick=()=>pending?send():review();
 if(!metadataReady){root.querySelectorAll('[data-field=category],#reviewBtn,#mobileReview').forEach(x=>x.disabled=true);}
 if(pending)root.querySelectorAll('input,select,textarea,[data-remove],[data-duplicate],[data-file-remove],#addItem,#clearDraft').forEach(x=>x.disabled=true);
 }
 function validate(){root.querySelectorAll('.error').forEach(x=>x.textContent='');root.querySelectorAll('[aria-invalid]').forEach(x=>x.removeAttribute('aria-invalid'));let first=null;items.forEach(it=>{const cat=categories.find(c=>c.Code===it.category);const errors=[];if(!cat)errors.push(['category','เลือกประเภทค่าใช้จ่าย']);if(!it.expenseDate||it.expenseDate>todayYMD()||it.expenseDate<'2020-01-01')errors.push(['expenseDate','เลือกวันที่ใช้จ่ายจริง ไม่เกินวันนี้']);const field=it.category==='FUEL'?'mileageKm':'amount';if(!Number.isFinite(Number(it[field]))||Number(it[field])<=0)errors.push([field,'กรอกตัวเลขมากกว่า 0']);if(cat?.NeedReceipt==='YES'&&!it.receipts.length)errors.push(['files','ประเภทนี้ต้องแนบใบเสร็จ']);if(cat?.NeedClaimForm==='YES')['venue','occasion','attendees'].forEach(f=>{if(!String(it[f]||'').trim())errors.push([f,'กรอกข้อมูลนี้ให้ครบ']);});errors.forEach(([f,msg])=>{const el=document.getElementById(it.id+'-'+f);document.getElementById(it.id+'-'+f+'-error').textContent=msg;el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby',it.id+'-'+f+'-error');el.closest('details').open=true;if(!first)first=el;});});if(first){first.focus();first.scrollIntoView({block:'center',behavior:'smooth'});return false;}return true;}
 async function review(){if(!validate())return;const fileBytes=items.reduce((sum,it)=>sum+it.receipts.reduce((a,f)=>a+Math.floor(f.base64.split(',')[1].length*3/4),0),0);if(fileBytes>20*1024*1024){showToast('ไฟล์รวมเกิน 20 MB กรุณาลดขนาดไฟล์หรือแบ่งคำขอ','error');return;}const d=document.createElement('dialog');d.className='review-dialog';d.innerHTML=`<div class="eyebrow">REVIEW YOUR REQUEST</div><h2>ตรวจสอบก่อนส่ง</h2><p class="subtle">${esc(session.Name)} · ผู้รับอนุมัติ ${esc(approver?.name||approver?.email||'ตามประเภท')}</p><div class="review-list">${items.map(it=>`<div class="review-row"><div>${esc(catTH(it.category))}<small>${esc(it.expenseDate)} · ใบเสร็จ ${it.receipts.length} ไฟล์</small></div><b>${formatCurrency(amount(it))}</b></div>`).join('')}<div class="review-row review-total"><span>รวม${items.some(it=>it.category==='FUEL')?'ประมาณการ':''}</span><span>${formatCurrency(total())} บาท</span></div></div><div class="dialog-actions"><button class="btn btn-secondary" id="backToForm">กลับไปแก้ไข</button><button class="btn btn-primary" id="confirmSend">ยืนยันส่งคำขอ</button></div>`;document.body.append(d);d.querySelector('#backToForm').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('#confirmSend').onclick=async()=>{pending={batchId:'BATCH-'+crypto.randomUUID(),staffEmail:session.Email,items:structuredClone(items).map(({id,...it})=>it)};try{await save();}catch(e){pending=null;showToast('บันทึกร่างก่อนส่งไม่สำเร็จ กรุณาตรวจพื้นที่จัดเก็บแล้วลองอีกครั้ง','error');return;}d.close();render();send();};d.showModal();}
 async function send(){if(busy)return;if(!navigator.onLine){showToast('ยังออฟไลน์ กรุณาเชื่อมต่ออินเทอร์เน็ตแล้วส่งอีกครั้ง','error');return;}busy=true;document.getElementById('reviewBtn').disabled=true;document.getElementById('mobileReview').disabled=true;showLoading('กำลังบันทึกคำขอ กรุณารอสักครู่');try{const r=await submitBatch(pending);if(!r.ok||(r.items||[]).length!==pending.items.length)throw new Error('ผลการบันทึกยังไม่ครบ กรุณาติดต่อผู้ดูแลพร้อมรหัสชุด '+pending.batchId);const ids=r.items.map(x=>x.id);await saveChain.catch(()=>{});await DraftStore.remove(key);localStorage.removeItem('exion_draft_'+session.Email.toLowerCase());pending=null;hideLoading();root.innerHTML=`<div class="card result-success"><div class="success-mark">${icon('check')}</div><div class="eyebrow">REQUEST SUBMITTED</div><h1>ส่งคำขอเรียบร้อยแล้ว</h1><p>บันทึกครบ ${ids.length} รายการ<br>ติดตามผลและรายละเอียดได้ในคำขอของฉัน</p><div class="review-total">${formatCurrency(r.items.reduce((a,x)=>a+Number(x.amount||0),0))} บาท</div><p>${ids.map(esc).join('<br>')}</p><div class="dialog-actions"><a class="btn btn-secondary" href="submit.html">สร้างคำขอใหม่</a><a class="btn btn-primary" href="status.html">ติดตามคำขอ →</a></div></div>`;}catch(e){hideLoading();if(e.code==='VALIDATION'){pending=null;save();}render();showToast(e.message+' · ร่างและไฟล์แนบยังอยู่','error');}finally{busy=false;}}
})();
