function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function pageHeading(title,description,action){return `<div class="page-heading"><div><div class="eyebrow">EXION WORKSPACE</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div>${action||''}</div>`;}
function emptyState(title,message,href,label){return `<div class="empty">${icon('inbox')}<div class="title">${esc(title)}</div><div class="sub">${esc(message)}</div>${href?`<a class="btn btn-secondary btn-sm" style="width:auto;margin-top:12px" href="${esc(href)}">${esc(label)}</a>`:''}</div>`;}
const ROLE_LABELS={staff:'พนักงาน',manager:'หัวหน้างาน',senior:'ผู้อนุมัติ',gm:'ผู้บริหาร',accountant:'บัญชี',viewer:'ผู้ดูรายงาน'};
async function renderWorkspaceNav(active){
 const s=getSession();if(!s)return;const path=location.pathname.split('/').pop()||'index.html';const approval=s.isManager||s.isSenior||s.isGM||s.isAccountant;
 const links=[['home','index.html','หน้าแรก','home'],['new','submit.html','สร้างคำขอ','plus'],['status','status.html','คำขอของฉัน','receipt'],['approvals','approvals.html','งานอนุมัติ','inbox'],['periods','periods.html','รอบเบิกและการจ่ายเงิน','list'],['petty','pc-home.html','เงินสดย่อย','car'],['summary','summary.html','รายงานภาพรวม','globe'],['team','my-team.html','ทีมของฉัน','user'],['profile','profile.html','บัญชีและลายเซ็น','user']].filter(x=>(x[0]!=='approvals'||approval)&&(x[0]!=='team'||s.isManager||s.isSenior||s.isGM));
 const key=path.startsWith('pc-')?'petty':/inbox|approve\.html|export-review/.test(path)?'approvals':path==='periods.html'?'periods':path==='approvals.html'?'approvals':active;
 document.querySelectorAll('.bottom-nav,.app-sidebar').forEach(x=>x.remove());document.body.classList.add('has-bottom-nav');
 const side=document.createElement('aside');side.className='app-sidebar';side.innerHTML=`<a class="sidebar-brand" href="index.html"><img src="icons/logo.png" alt="EXION"><small>EXPENSE WORKSPACE</small></a><div class="sidebar-section">พื้นที่ทำงาน</div><nav aria-label="เมนูหลัก">${links.map(x=>`<a class="side-link ${x[0]===key?'active':''}" ${x[0]===key?'aria-current="page"':''} href="${x[1]}">${icon(x[3])}<span>${x[2]}</span></a>`).join('')}</nav><div class="sidebar-footer">${esc(ROLE_LABELS[s.role]||'พนักงาน')} · ${esc(s.Department||'EXION')}<br><span style="font-size:10px">EXION (Thailand) · Workspace 8.0.6</span></div>`;document.body.append(side);
 const mobile=[links[0],links[1],links[2],links.find(x=>x[0]===(approval?'approvals':'periods')),['more','menu.html','เพิ่มเติม','more']];const nav=document.createElement('nav');nav.className='bottom-nav';nav.setAttribute('aria-label','เมนูหลัก');nav.innerHTML=mobile.map(x=>`<a class="nav-item ${x[0]===key?'active':''}" href="${x[1]}" ${x[0]===key?'aria-current="page"':''}>${icon(x[3])}<span>${x[2]}</span></a>`).join('');document.body.append(nav);
 const h=document.querySelector('.header');if(h&&!h.querySelector('.header-user')){const a=document.createElement('a');a.className='header-user';a.href='profile.html';a.innerHTML=`<span class="user-label">${esc(s.Name)}</span><span class="user-initial">${esc(initials(s.Name))}</span>`;a.setAttribute('aria-label','บัญชีของฉัน');h.append(a);}renderNotifBell();return links;
}
renderBottomNav=renderWorkspaceNav;
statusTH=value=>({pending:'รออนุมัติ',approved:'อนุมัติแล้ว',rejected:'ไม่อนุมัติ',finalized:'ส่งบิลแล้ว',preapprove:'ขออนุมัติงบ',paid:'จ่ายแล้ว',cancelled:'ยกเลิก'}[String(value||'').toLowerCase()]||String(value||'-'));
statusBadge=value=>`<span class="badge ${['pending','approved','rejected','finalized','preapprove','paid','cancelled'].includes(String(value).toLowerCase())?String(value).toLowerCase():''}">${esc(statusTH(value))}</span>`;
window.addEventListener('DOMContentLoaded',()=>{
 const banner=document.createElement('div');banner.className='offline-banner';banner.setAttribute('role','status');banner.textContent='ออฟไลน์ — กรอกร่างต่อได้ เชื่อมต่ออินเทอร์เน็ตก่อนส่งคำขอ';document.body.prepend(banner);const update=()=>banner.hidden=navigator.onLine;update();window.addEventListener('online',update);window.addEventListener('offline',update);
 const main=document.querySelector('.container');if(main){main.id=main.id||'main-content';main.setAttribute('role','main');const skip=document.createElement('a');skip.className='skip-link';skip.href='#'+main.id;skip.textContent='ข้ามไปเนื้อหา';document.body.prepend(skip);}
 document.querySelectorAll('.field label').forEach(l=>{const input=l.parentElement.querySelector('input,select,textarea');if(input?.id)l.htmlFor=input.id;});
 const file=location.pathname.split('/').pop();const descriptions={'status.html':['คำขอของฉัน','ติดตามสถานะ ตรวจสอบรายละเอียด และจัดการรายการของคุณ'],'pre-approve.html':['ขออนุมัติงบ','ขอวงเงินค่ารับรองหรือกอล์ฟก่อนเริ่มใช้จ่าย'],'pre-approves.html':['งบที่ขออนุมัติ','ติดตามวงเงินและส่งใบเสร็จเมื่อใช้จ่ายจริง'],'profile.html':['บัญชีและลายเซ็น','ข้อมูลส่วนตัว ลายเซ็น และความปลอดภัยของบัญชี'],'periods.html':['รอบเบิกและการจ่ายเงิน','ตรวจสอบช่วงวันที่ ขออนุมัติรอบเบิก และดาวน์โหลดเอกสาร'],'pc-home.html':['เงินสดย่อย','ยอดคงเหลือและรายการที่ต้องดำเนินการ'],'pc-request.html':['ขอเบิกเงินสดย่อย','กรอกรายละเอียดและแนบหลักฐานการใช้จ่าย'],'summary.html':['รายงานภาพรวม','ดูค่าใช้จ่ายตามช่วงเวลา ประเภท และผู้ใช้งาน'],'my-team.html':['ทีมของฉัน','ข้อมูลทีม รายงาน และการจัดการบัญชี'],'pc-fund.html':['จัดการกล่องเงินสด','เติมเงิน เคลียร์บิล และตรวจนับเงินสด'],'pc-msbc.html':['รายงานเงินสดย่อย','ตรวจสอบรายการและส่งออกข้อมูลสำหรับบัญชี']};if(main&&descriptions[file])main.insertAdjacentHTML('afterbegin',pageHeading(...descriptions[file]));
 if(file==='menu.html'&&main)renderWorkspaceNav('more').then(links=>{main.innerHTML=pageHeading('พื้นที่ทำงาน','ทุกเมนูของคุณ อยู่ที่เดียว')+`<div class="quick-grid">${links.map(x=>`<a class="quick-link" href="${x[1]}">${icon(x[3])}<strong>${x[2]}</strong></a>`).join('')}</div><button id="menuLogout" class="btn btn-secondary">ออกจากระบบ</button>`;document.getElementById('menuLogout').onclick=logout;});
});
async function logout(){try{await apiPost('logout');}catch(e){}clearSession();location.href='index.html';}
async function confirmDialog(title,message,label='ยืนยัน'){const d=document.createElement('dialog');d.className='review-dialog';d.innerHTML=`<h2>${esc(title)}</h2><p class="subtle" style="white-space:pre-line">${esc(message)}</p><div class="dialog-actions"><button class="btn btn-secondary" data-cancel>กลับไปแก้ไข</button><button class="btn btn-primary" data-yes>${esc(label)}</button></div>`;document.body.append(d);return new Promise(resolve=>{let result=false;d.querySelector('[data-yes]').onclick=()=>{result=true;d.close();};d.querySelector('[data-cancel]').onclick=()=>d.close();d.onclose=()=>{d.remove();resolve(result);};d.showModal();});}
function requestTimeline(r){const steps=[['ส่งคำขอแล้ว',r.Timestamp,r.StaffName,true],['ผลการอนุมัติ',r.ApprovedAt||r.ManagerApprovedAt,r.ApprovedBy||r.ManagerEmail,['Approved','Rejected','Finalized'].includes(r.Status)]];return `<div class="timeline">${steps.map(([title,date,who,done])=>`<div class="timeline-step ${done?'done':''}"><div><strong>${esc(title)}${title==='ผลการอนุมัติ'?' · '+esc(statusTH(r.Status)):''}</strong><small>${date?esc(formatDate(date)):done?'ดำเนินการแล้ว':'รอดำเนินการ'}${who?' · '+esc(who):''}</small></div></div>`).join('')}<div class="subtle">สถานะการจ่ายเงินดูที่ <a href="periods.html">รอบเบิกและการจ่ายเงิน →</a></div></div>`;}

// Snapshot labels stay visible until the user explicitly refreshes; never replace a draft.
let latestDataStatus=null;
window.addEventListener('exion:data-status',e=>{
 latestDataStatus=e.detail;
 let bar=document.getElementById('dataFreshness');
 if(!bar){bar=document.createElement('div');bar.id='dataFreshness';bar.className='data-freshness';bar.setAttribute('role','status');const main=document.querySelector('.container');if(!main)return;main.prepend(bar);}
 const time=new Date(e.detail.at).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});
 bar.replaceChildren();const label=document.createElement('span');
 label.textContent=e.detail.state==='changed'?'ข้อมูลเปลี่ยนจากอีกแท็บ · กดรีเฟรชเพื่อแสดงข้อมูลล่าสุด':'แสดงข้อมูลที่โหลดไว้ '+time+' · '+(e.detail.state==='cached'?'กำลังตรวจข้อมูลล่าสุด':e.detail.state==='error'?'อัปเดตไม่สำเร็จ':'กดรีเฟรชเพื่อแสดงข้อมูลล่าสุด');bar.append(label);
 const button=document.createElement('button');button.type='button';button.className='btn btn-secondary btn-sm';button.textContent='รีเฟรช';button.onclick=()=>{if(document.querySelector('form,.expense-card')){confirmDialog('รีเฟรชข้อมูล?','หากมีข้อมูลที่ยังไม่บันทึก กรุณาบันทึกก่อนรีเฟรช','รีเฟรช').then(ok=>{if(ok)refreshWorkspaceData();});}else refreshWorkspaceData();};bar.append(button);
});

new MutationObserver(()=>{if(latestDataStatus&&getSession()&&!document.getElementById('dataFreshness')&&document.querySelector('.container'))window.dispatchEvent(new CustomEvent('exion:data-status',{detail:latestDataStatus}));}).observe(document.body,{childList:true,subtree:true});
