(async()=>{const s=getSession();if(!s)return;const el=document.getElementById('paymentRows');try{const rows=await apiGet('getMyExportRequests',{email:s.Email});el.innerHTML=rows.length?rows.map(r=>`<div class="review-row"><div>${esc(r.Year)} / ${esc(r.Month)}<small>${esc(r.ID)} · ${esc(toYMD(r.PeriodStart))} – ${esc(toYMD(r.PeriodEnd))}</small></div><div>${statusBadge(r.PaidAt||r.PaymentStatus==='Paid'||r.Paid===true?'Paid':r.OverallStatus)}<small>${r.PaidAt?'จ่ายเมื่อ '+esc(formatDate(r.PaidAt)):r.OverallStatus==='Approved'?'อนุมัติเอกสารแล้ว · รอการบันทึกจ่าย':''}</small></div></div>`).join(''):emptyState('ยังไม่มีรอบเบิก','เลือกรอบด้านบนเพื่อเตรียมเอกสารเบิกครั้งแรก');}catch(e){renderError(el,e.message,()=>location.reload());}})();
(async()=>{
 const s=getSession();if(!s||!(s.isAccountant||s.isGM))return;
 const section=document.createElement('section');section.className='card';section.id='financePayments';document.querySelector('.container').prepend(section);
 async function load(){section.innerHTML='<h3>สำหรับบัญชี · รอบเบิกรอจ่าย</h3><div class="subtle">กำลังโหลด...</div>';try{const rows=await fetchUnpaidExports(s.Email);section.innerHTML='<h3>สำหรับบัญชี · รอบเบิกรอจ่าย</h3><p class="subtle">บันทึกหลังโอนเงินเรียบร้อยแล้วเท่านั้น</p>'+ (rows.length?rows.map(r=>`<div class="review-row"><div>${esc(r.StaffName)}<small>${esc(r.ID)} · ${esc(r.Month)}/${esc(r.Year)}</small></div><div>${formatCurrency(r.TotalAmount)} บาท<br><button class="btn btn-secondary btn-sm" data-pay="${esc(r.ID)}" style="margin-top:7px">บันทึกว่าจ่ายแล้ว</button></div></div>`).join(''):emptyState('ไม่มีรอบเบิกรอจ่าย','รายการจะปรากฏหลังอนุมัติเอกสารเบิกแล้ว'));
 section.querySelectorAll('[data-pay]').forEach(b=>b.onclick=async()=>{const r=rows.find(x=>x.ID===b.dataset.pay);if(!await confirmDialog('ยืนยันว่าจ่ายเงินแล้ว?',r.StaffName+' · '+formatCurrency(r.TotalAmount)+' บาท\nบันทึกเมื่อโอนเงินจริงเรียบร้อยแล้ว','บันทึกการจ่าย'))return;b.disabled=true;try{await markExportPaid(s.Email,r.ID);showToast('บันทึกการจ่ายเงินเรียบร้อย','success');await load();}catch(e){showToast(e.message,'error');b.disabled=false;}});
 }catch(e){renderError(section,e.message,load);}}
 await load();
})();
